/*** Role ***/
CREATE TABLE IF NOT EXISTS roles (
  id         BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL,
  updated_at TIMESTAMP WITHOUT TIME ZONE,
  title VARCHAR(255) UNIQUE,
  code VARCHAR(255) UNIQUE
);

/*** User ***/
CREATE TABLE IF NOT EXISTS users (
  id         BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL,
  updated_at TIMESTAMP WITHOUT TIME ZONE,
  email VARCHAR(255) UNIQUE,
  password VARCHAR(255),
  phone VARCHAR(255),
  image_url VARCHAR(255),
  auth_provider SMALLINT,
  provider_id VARCHAR(255),
  email_verified  BOOLEAN DEFAULT FALSE,
  first_name VARCHAR(255),
  last_name VARCHAR(255),
  enabled BOOLEAN DEFAULT FALSE
);

/*** User - Role ***/
CREATE TABLE IF NOT EXISTS user_roles (
  user_id BIGINT REFERENCES users (id) ON UPDATE CASCADE ON DELETE CASCADE ,
  role_id BIGINT REFERENCES roles (id) ON UPDATE CASCADE ON DELETE CASCADE
);